### ISSUE TITLE
Can't get two AM2320 sensors working with Raspberry Pico

### ISSUE THREAD

**Issue by kcajjones** [penguintutor/rpi-pico-temperature#1] opened 2023-02-02 23:37 UTC
I've successfully got a Raspberry Pico to read humidity and temperature via Micropython but cannot get a second sensor to work via the I2C1 pins, using the library you made on here.
I get the following error when trying to read the second sensor:

> Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "am2320.py", line 44, in measure
OSError: [Errno 5] EIO

Any help would be greatly appreciated

**Comment by penguintutor** [comment] 2023-02-03 14:45
The error message is from the library at: https://github.com/mcauser/micropython-am2320 
I only included it in this repository for convenience.

Looking at that source code then that instruction is just a standard i2c.writeto(), so I don't think that the problem is with that library. 

What code are you using to create your two I2C instances? 
How are you calling the library?
Does the second instance work if you don't use I2C0? Is the problem only when you are running both?

**Comment by kcajjones** [comment] 2023-02-15 18:59
It seems to be a bug with ether Thonny v4.0.2 or Micropython v1.19.1 or my PC.
It comes up with the error message until I stop/restart backend on Thony, or I unplug the pico and plug the USB cable back in.

The code works perfectly. Thanks for sharing the library files!

Here's my code for reference:

`import utime
import am2320
import machine
from machine import I2C, Pin

i2c = I2C(0,sda=Pin(16), scl=Pin(17), freq=100000)
sensor1 = am2320.AM2320(i2c)
sensor1.measure()
print("Temperature Sensor 1 is",sensor1.temperature())
print("Humidity Sensor 1 is",sensor1.humidity(),"%")
utime.sleep_ms(500)

i2c1 = I2C(1,sda=Pin(14), scl=Pin(15), freq=100000)
sensor2 = am2320.AM2320(i2c)
sensor2.measure()
print("Temperature Sensor 2 is",sensor2.temperature())
print("Humidity Sensor 2 is",sensor2.humidity(),"%")
utime.sleep_ms(500)

fan1 = machine.PWM(machine.Pin(0))
fan1.freq(25000)
fan1.duty_u16(0)
print("Upper fan speed is",fan1.duty_u16())

fan2 = machine.PWM(machine.Pin(4))
fan2.freq(25000)
fan2.duty_u16(0)
print("Lower fan speed is",fan2.duty_u16())

utime.sleep_ms(500)

while True:       
    if sensor1.temperature() <=22:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(0)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 22:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(16490)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 23:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(20000)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 24:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(25000)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 25:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(30000)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 26:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(40000)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 27:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(50000)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)

    if sensor1.temperature() >= 28:
        sensor1.measure()
        print("Temperature Sensor 1 is",sensor1.temperature())
        print("Humidity Sensor 1 is",sensor1.humidity(),"%")
        fan1.duty_u16(65535)
        print("Setting fan to",fan1.duty_u16())
        utime.sleep_ms(1500)
        
    if sensor2.temperature() <=22:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(0)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)
    
    if sensor2.temperature() >= 22:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(16490)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)

    if sensor2.temperature() >= 23:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(20000)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)

    if sensor2.temperature() >= 24:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(25000)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)

    if sensor2.temperature() >= 25:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(30000)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)

    if sensor2.temperature() >= 26:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(40000)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)

    if sensor2.temperature() >= 27:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(50000)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)

    if sensor2.temperature() >= 28:
        sensor2.measure()
        print("Temperature Sensor 2 is",sensor2.temperature())
        print("Humidity Sensor 2 is",sensor2.humidity(),"%")
        fan2.duty_u16(65535)
        print("Setting lower fan to",fan2.duty_u16())
        utime.sleep_ms(1500)`

**Comment by penguintutor** [comment] 2023-02-15 22:21
Closing the issue as it is not related to any of the specific code for the rpi-pico-temperature project.

**Closed as completed by penguintutor** 2023-02-15 22:21 UTC
